export enum BpkTypography{
    subheading = "Body/Subheading",
    bodyDefault = "Body/Body Default",
    bodyLongform = "Body/Body Longform",
    caption = "Body/Caption",
    footnote = "Body/Footnote",
    heading1 = "Heading/Heading 1",
    heading2 = "Heading/Heading 2",
    heading3 = "Heading/Heading 3",
    heading4 = "Heading/Heading 4",
    heading5 = "Heading/Heading 5",
    hero1 = "Hero/Hero 1",
    hero2 = "Hero/Hero 2",
    hero3 = "Hero/Hero 3",
    hero4 = "Hero/Hero 4",
    hero5 = "Hero/Hero 5",
    label1 = "Label/Label 1",
    label2 = "Label/Label 2",
    label3 = "Label/Label 3",
}